name: crawl depop
on:
  schedule:
        - cron: '9,24,39,54 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python crawl.py
        env:
          ICLOUD_USER: ${{ secrets.ICLOUD_USER }}
          ICLOUD_PASS: ${{ secrets.ICLOUD_PASS }}
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
          SECRET: ${{ secrets.SECRET }}
